### ISSUE TITLE
Hide another section in profile related to posts

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-theme#10]
![Bildschirmfoto 2022-07-14 um 13 52 43](https://user-images.githubusercontent.com/1942953/178976871-09420e29-4c2e-4335-b05b-e4b6a5ad503c.png)

Is this related to posts section we are hiding now with #3? The arrow looks like pointing to the text area that is removed. Do you think this confuses users and we should also hide that?

**Comment by donni106** [comment]
Ouh and if I click on `Stream` the javascript seems not to work and I see posts and filter again:

![Bildschirmfoto 2022-07-14 um 14 04 56](https://user-images.githubusercontent.com/1942953/178978427-d631691c-1eb1-4707-9512-3babeb9d6d52.png)

**Comment by donni106** [comment]
![Bildschirmfoto 2022-07-14 um 14 06 26](https://user-images.githubusercontent.com/1942953/178978569-f35c63c2-f09a-4b20-945f-dacbfb317a63.png)

**Comment by gaurav-handysolver** [comment]
> Ouh and if I click on `Stream` the javascript seems not to work and I see posts and filter again:
> 
> ![Bildschirmfoto 2022-07-14 um 14 04 56](https://user-images.githubusercontent.com/1942953/178978427-d631691c-1eb1-4707-9512-3babeb9d6d52.png)

Hi @donni106 
Okay, we will figure it out

**Comment by donni106** [comment]
sure, new branch is perfect.
i think the script should not define new variables but instead do `document.getElementById("post_section").remove();`?

**Comment by gaurav-handysolver** [comment]
> sure, new branch is perfect. i think the script should not define new variables but instead do `document.getElementById("post_section").remove();`?

Hi @donni106 
Yes, you are right now we are not using any variable for removing the section.

**Comment by gaurav-handysolver** [comment]
> ![Bildschirmfoto 2022-07-14 um 13 52 43](https://user-images.githubusercontent.com/1942953/178976871-09420e29-4c2e-4335-b05b-e4b6a5ad503c.png)
> 
> Is this related to posts section we are hiding now with #3? The arrow looks like pointing to the text area that is removed. Do you think this confuses users and we should also hide that?

Hi @donni106 
It is showing blank becasue you don't create any event on calendar. yes it is showing post details also (which we hide).

![image](https://user-images.githubusercontent.com/103625795/178988354-d89c33ef-b75c-4542-ad6c-7ce7631f9541.png)

And we can hide this header information from user's profile 

![image](https://user-images.githubusercontent.com/103625795/178988561-668dc880-7442-4d1e-8d1d-74e8e1175cd1.png)

**Comment by donni106** [comment]
> And we can hide this header information from user's profile
> 
> ![image](https://user-images.githubusercontent.com/103625795/178988561-668dc880-7442-4d1e-8d1d-74e8e1175cd1.png)

no please don't! this needs to stay.
i was asking about that part

![Bildschirmfoto 2022-07-14 um 15 03 14](https://user-images.githubusercontent.com/1942953/178988912-6088dfbc-8ce6-4f67-ad87-0a99e4d9e1a2.png)

**Comment by gaurav-handysolver** [comment]
> 

Okay, got it
